// Code generated by hertz generator.

package car

import (
	"context"

	"github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/errno"
	"github.com/CyanAsterisk/FreeCar/server/cmd/api/global"
	"github.com/CyanAsterisk/FreeCar/server/cmd/car/kitex_gen/car"
	"github.com/cloudwego/hertz/pkg/app"
)

// CreateCar .
// @router /v1/car [POST]
func CreateCar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req car.CreateCarRequest
	aid, flag := c.Get("accountID")
	if !flag {
		errno.SendResponse(c, errno.ParamErr, nil)
	}
	req.AccountId = aid.(int64)

	resp, err := global.CarClient.CreateCar(ctx, &req)
	if err != nil {
		errno.SendResponse(c, errno.RequestServerFail, nil)
	}
	errno.SendResponse(c, errno.Success, resp)
}

// GetCar .
// @router /v1/car [GET]
func GetCar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req car.GetCarRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		errno.SendResponse(c, errno.BindAndValidateFail, nil)
		return
	}
	aid, flag := c.Get("accountID")
	if !flag {
		errno.SendResponse(c, errno.ParamErr, nil)
	}
	req.AccountId = aid.(int64)

	resp, err := global.CarClient.GetCar(ctx, &req)
	if err != nil {
		errno.SendResponse(c, errno.RequestServerFail, nil)
	}
	errno.SendResponse(c, errno.Success, resp)
}
