// Code generated by hertz generator.

package Car

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _carMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcarMw() []app.HandlerFunc {
	// your code...
	return nil
}
