/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.lanlance.freecartrade.rpc.thrift_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2025-04-14")
public class BaseResponse implements org.apache.thrift.TBase<BaseResponse, BaseResponse._Fields>, java.io.Serializable, Cloneable, Comparable<BaseResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BaseResponse");

  private static final org.apache.thrift.protocol.TField STATUS_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("status_code", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField STATUS_MSG_FIELD_DESC = new org.apache.thrift.protocol.TField("status_msg", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BaseResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BaseResponseTupleSchemeFactory();

  public long status_code; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String status_msg; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STATUS_CODE((short)1, "status_code"),
    STATUS_MSG((short)2, "status_msg");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATUS_CODE
          return STATUS_CODE;
        case 2: // STATUS_MSG
          return STATUS_MSG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STATUS_CODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATUS_CODE, new org.apache.thrift.meta_data.FieldMetaData("status_code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.STATUS_MSG, new org.apache.thrift.meta_data.FieldMetaData("status_msg", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BaseResponse.class, metaDataMap);
  }

  public BaseResponse() {
  }

  public BaseResponse(
    long status_code,
    java.lang.String status_msg)
  {
    this();
    this.status_code = status_code;
    setStatus_codeIsSet(true);
    this.status_msg = status_msg;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BaseResponse(BaseResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.status_code = other.status_code;
    if (other.isSetStatus_msg()) {
      this.status_msg = other.status_msg;
    }
  }

  public BaseResponse deepCopy() {
    return new BaseResponse(this);
  }

  @Override
  public void clear() {
    setStatus_codeIsSet(false);
    this.status_code = 0;
    this.status_msg = null;
  }

  public long getStatus_code() {
    return this.status_code;
  }

  public BaseResponse setStatus_code(long status_code) {
    this.status_code = status_code;
    setStatus_codeIsSet(true);
    return this;
  }

  public void unsetStatus_code() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STATUS_CODE_ISSET_ID);
  }

  /** Returns true if field status_code is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus_code() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STATUS_CODE_ISSET_ID);
  }

  public void setStatus_codeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STATUS_CODE_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getStatus_msg() {
    return this.status_msg;
  }

  public BaseResponse setStatus_msg(@org.apache.thrift.annotation.Nullable java.lang.String status_msg) {
    this.status_msg = status_msg;
    return this;
  }

  public void unsetStatus_msg() {
    this.status_msg = null;
  }

  /** Returns true if field status_msg is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus_msg() {
    return this.status_msg != null;
  }

  public void setStatus_msgIsSet(boolean value) {
    if (!value) {
      this.status_msg = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case STATUS_CODE:
      if (value == null) {
        unsetStatus_code();
      } else {
        setStatus_code((java.lang.Long)value);
      }
      break;

    case STATUS_MSG:
      if (value == null) {
        unsetStatus_msg();
      } else {
        setStatus_msg((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case STATUS_CODE:
      return getStatus_code();

    case STATUS_MSG:
      return getStatus_msg();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case STATUS_CODE:
      return isSetStatus_code();
    case STATUS_MSG:
      return isSetStatus_msg();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof BaseResponse)
      return this.equals((BaseResponse)that);
    return false;
  }

  public boolean equals(BaseResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_status_code = true;
    boolean that_present_status_code = true;
    if (this_present_status_code || that_present_status_code) {
      if (!(this_present_status_code && that_present_status_code))
        return false;
      if (this.status_code != that.status_code)
        return false;
    }

    boolean this_present_status_msg = true && this.isSetStatus_msg();
    boolean that_present_status_msg = true && that.isSetStatus_msg();
    if (this_present_status_msg || that_present_status_msg) {
      if (!(this_present_status_msg && that_present_status_msg))
        return false;
      if (!this.status_msg.equals(that.status_msg))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(status_code);

    hashCode = hashCode * 8191 + ((isSetStatus_msg()) ? 131071 : 524287);
    if (isSetStatus_msg())
      hashCode = hashCode * 8191 + status_msg.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(BaseResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetStatus_code()).compareTo(other.isSetStatus_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status_code, other.status_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStatus_msg()).compareTo(other.isSetStatus_msg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus_msg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status_msg, other.status_msg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BaseResponse(");
    boolean first = true;

    sb.append("status_code:");
    sb.append(this.status_code);
    first = false;
    if (!first) sb.append(", ");
    sb.append("status_msg:");
    if (this.status_msg == null) {
      sb.append("null");
    } else {
      sb.append(this.status_msg);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BaseResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BaseResponseStandardScheme getScheme() {
      return new BaseResponseStandardScheme();
    }
  }

  private static class BaseResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<BaseResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BaseResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATUS_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.status_code = iprot.readI64();
              struct.setStatus_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STATUS_MSG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.status_msg = iprot.readString();
              struct.setStatus_msgIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BaseResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(STATUS_CODE_FIELD_DESC);
      oprot.writeI64(struct.status_code);
      oprot.writeFieldEnd();
      if (struct.status_msg != null) {
        oprot.writeFieldBegin(STATUS_MSG_FIELD_DESC);
        oprot.writeString(struct.status_msg);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BaseResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BaseResponseTupleScheme getScheme() {
      return new BaseResponseTupleScheme();
    }
  }

  private static class BaseResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<BaseResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BaseResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetStatus_code()) {
        optionals.set(0);
      }
      if (struct.isSetStatus_msg()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetStatus_code()) {
        oprot.writeI64(struct.status_code);
      }
      if (struct.isSetStatus_msg()) {
        oprot.writeString(struct.status_msg);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BaseResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.status_code = iprot.readI64();
        struct.setStatus_codeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.status_msg = iprot.readString();
        struct.setStatus_msgIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

