/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.lanlance.freecartrade.rpc.thrift_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2025-04-14")
public class PayRequest implements org.apache.thrift.TBase<PayRequest, PayRequest._Fields>, java.io.Serializable, Cloneable, Comparable<PayRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PayRequest");

  private static final org.apache.thrift.protocol.TField ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("account_id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FEE_CENT_FIELD_DESC = new org.apache.thrift.protocol.TField("fee_cent", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PayRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PayRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String account_id; // required
  public int fee_cent; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACCOUNT_ID((short)1, "account_id"),
    FEE_CENT((short)2, "fee_cent");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACCOUNT_ID
          return ACCOUNT_ID;
        case 2: // FEE_CENT
          return FEE_CENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FEE_CENT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("account_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FEE_CENT, new org.apache.thrift.meta_data.FieldMetaData("fee_cent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PayRequest.class, metaDataMap);
  }

  public PayRequest() {
  }

  public PayRequest(
    java.lang.String account_id,
    int fee_cent)
  {
    this();
    this.account_id = account_id;
    this.fee_cent = fee_cent;
    setFee_centIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PayRequest(PayRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetAccount_id()) {
      this.account_id = other.account_id;
    }
    this.fee_cent = other.fee_cent;
  }

  public PayRequest deepCopy() {
    return new PayRequest(this);
  }

  @Override
  public void clear() {
    this.account_id = null;
    setFee_centIsSet(false);
    this.fee_cent = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAccount_id() {
    return this.account_id;
  }

  public PayRequest setAccount_id(@org.apache.thrift.annotation.Nullable java.lang.String account_id) {
    this.account_id = account_id;
    return this;
  }

  public void unsetAccount_id() {
    this.account_id = null;
  }

  /** Returns true if field account_id is set (has been assigned a value) and false otherwise */
  public boolean isSetAccount_id() {
    return this.account_id != null;
  }

  public void setAccount_idIsSet(boolean value) {
    if (!value) {
      this.account_id = null;
    }
  }

  public int getFee_cent() {
    return this.fee_cent;
  }

  public PayRequest setFee_cent(int fee_cent) {
    this.fee_cent = fee_cent;
    setFee_centIsSet(true);
    return this;
  }

  public void unsetFee_cent() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FEE_CENT_ISSET_ID);
  }

  /** Returns true if field fee_cent is set (has been assigned a value) and false otherwise */
  public boolean isSetFee_cent() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FEE_CENT_ISSET_ID);
  }

  public void setFee_centIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FEE_CENT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ACCOUNT_ID:
      if (value == null) {
        unsetAccount_id();
      } else {
        setAccount_id((java.lang.String)value);
      }
      break;

    case FEE_CENT:
      if (value == null) {
        unsetFee_cent();
      } else {
        setFee_cent((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ACCOUNT_ID:
      return getAccount_id();

    case FEE_CENT:
      return getFee_cent();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ACCOUNT_ID:
      return isSetAccount_id();
    case FEE_CENT:
      return isSetFee_cent();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof PayRequest)
      return this.equals((PayRequest)that);
    return false;
  }

  public boolean equals(PayRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_account_id = true && this.isSetAccount_id();
    boolean that_present_account_id = true && that.isSetAccount_id();
    if (this_present_account_id || that_present_account_id) {
      if (!(this_present_account_id && that_present_account_id))
        return false;
      if (!this.account_id.equals(that.account_id))
        return false;
    }

    boolean this_present_fee_cent = true;
    boolean that_present_fee_cent = true;
    if (this_present_fee_cent || that_present_fee_cent) {
      if (!(this_present_fee_cent && that_present_fee_cent))
        return false;
      if (this.fee_cent != that.fee_cent)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAccount_id()) ? 131071 : 524287);
    if (isSetAccount_id())
      hashCode = hashCode * 8191 + account_id.hashCode();

    hashCode = hashCode * 8191 + fee_cent;

    return hashCode;
  }

  @Override
  public int compareTo(PayRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetAccount_id()).compareTo(other.isSetAccount_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccount_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.account_id, other.account_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFee_cent()).compareTo(other.isSetFee_cent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFee_cent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fee_cent, other.fee_cent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PayRequest(");
    boolean first = true;

    sb.append("account_id:");
    if (this.account_id == null) {
      sb.append("null");
    } else {
      sb.append(this.account_id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fee_cent:");
    sb.append(this.fee_cent);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PayRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PayRequestStandardScheme getScheme() {
      return new PayRequestStandardScheme();
    }
  }

  private static class PayRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<PayRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PayRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.account_id = iprot.readString();
              struct.setAccount_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FEE_CENT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.fee_cent = iprot.readI32();
              struct.setFee_centIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PayRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.account_id != null) {
        oprot.writeFieldBegin(ACCOUNT_ID_FIELD_DESC);
        oprot.writeString(struct.account_id);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FEE_CENT_FIELD_DESC);
      oprot.writeI32(struct.fee_cent);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PayRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PayRequestTupleScheme getScheme() {
      return new PayRequestTupleScheme();
    }
  }

  private static class PayRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<PayRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PayRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAccount_id()) {
        optionals.set(0);
      }
      if (struct.isSetFee_cent()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetAccount_id()) {
        oprot.writeString(struct.account_id);
      }
      if (struct.isSetFee_cent()) {
        oprot.writeI32(struct.fee_cent);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PayRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.account_id = iprot.readString();
        struct.setAccount_idIsSet(true);
      }
      if (incoming.get(1)) {
        struct.fee_cent = iprot.readI32();
        struct.setFee_centIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

