// Code generated by hertz generator.

package User

import (
	"context"

	"github.com/CyanAsterisk/FreeCar/server/shared/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/limiter"
	"github.com/hertz-contrib/requestid"
	"go.opentelemetry.io/otel/trace"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.JWTAuth(),
	}
}

func _userMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		// use gzip mw
		gzip.Gzip(gzip.DefaultCompression, gzip.WithExcludedExtensions([]string{".jpg", ".mp4", ".png"})),
		// use limiter mw
		limiter.AdaptiveLimit(limiter.WithCPUThreshold(900)),
		// use requestId mw & bind with traceId
		requestid.New(
			requestid.WithGenerator(func(ctx context.Context, c *app.RequestContext) string {
				traceID := trace.SpanFromContext(ctx).SpanContext().TraceID().String()
				return traceID
			}),
		),
	}
}

func __dminget_llusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __dminchangepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __dmingetsomeusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __dmin_dduserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __dmindeleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __dminupdateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __dminloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _login0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _miniMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.JWTAuth(),
	}
}

func _upload_vatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
