// Code generated by hertz generator.

package Api

import (
	"context"
	"fmt"

	"github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/errno"
	"github.com/CyanAsterisk/FreeCar/shared/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		// use recovery mw
		recovery.Recovery(recovery.WithRecoveryHandler(
			func(ctx context.Context, c *app.RequestContext, err interface{}, stack []byte) {
				hlog.SystemLogger().CtxErrorf(ctx, "[Recovery] err=%v\nstack=%s", err, stack)
				c.JSON(consts.StatusInternalServerError, utils.H{
					"code":    errno.BadRequest,
					"message": fmt.Sprintf("[Recovery] err=%v\nstack=%s", err, stack),
				})
			},
		)),
		middleware.JWTAuth(),
	}
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clearprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tripMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetripMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettripMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettripsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _profileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createprofilephotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clearprofilephotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _photoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completeprofilephotoMw() []app.HandlerFunc {
	// your code...
	return nil
}
