// Code generated by hertz generator.

package trip

import (
	"context"

	"github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/errno"
	"github.com/CyanAsterisk/FreeCar/server/cmd/api/global"
	"github.com/CyanAsterisk/FreeCar/server/cmd/trip/kitex_gen/trip"
	"github.com/cloudwego/hertz/pkg/app"
)

// CreateTrip .
// @router /v1/trip [POST]
func CreateTrip(ctx context.Context, c *app.RequestContext) {
	var err error
	var req trip.CreateTripRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		errno.SendResponse(c, errno.BindAndValidateFail, nil)
		return
	}
	aid, flag := c.Get("accountID")
	if !flag {
		errno.SendResponse(c, errno.ParamErr, nil)
	}
	req.AccountId = aid.(int64)

	resp, err := global.TripClient.CreateTrip(ctx, &req)
	if err != nil {
		errno.SendResponse(c, errno.RequestServerFail, nil)
		return
	}

	errno.SendResponse(c, errno.Success, resp)
}

// GetTrip .
// @router /v1/trip/:id [GET]
func GetTrip(ctx context.Context, c *app.RequestContext) {
	var err error
	var req trip.GetTripRequest
	aid, flag := c.Get("accountID")
	if !flag {
		errno.SendResponse(c, errno.ParamErr, nil)
	}
	req.AccountId = aid.(int64)
	req.Id = c.Param("id")

	resp, err := global.TripClient.GetTrip(ctx, &req)
	if err != nil {
		errno.SendResponse(c, errno.RequestServerFail, nil)
		return
	}

	errno.SendResponse(c, errno.Success, resp)
}

// GetTrips .
// @router /v1/trips [GET]
func GetTrips(ctx context.Context, c *app.RequestContext) {
	var err error
	var req trip.GetTripsRequest
	if err != nil {
		errno.SendResponse(c, errno.BindAndValidateFail, nil)
		return
	}
	aid, flag := c.Get("accountID")
	if !flag {
		errno.SendResponse(c, errno.ParamErr, nil)
	}
	req.AccountId = aid.(int64)

	resp, err := global.TripClient.GetTrips(ctx, &req)
	if err != nil {
		errno.SendResponse(c, errno.RequestServerFail, nil)
		return
	}

	errno.SendResponse(c, errno.Success, resp)
}

// UpdateTrip .
// @router /v1/trip/:id [PUT]
func UpdateTrip(ctx context.Context, c *app.RequestContext) {
	var err error
	var req trip.UpdateTripRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		errno.SendResponse(c, errno.BindAndValidateFail, nil)
		return
	}
	aid, flag := c.Get("accountID")
	if !flag {
		errno.SendResponse(c, errno.ParamErr, nil)
	}
	req.AccountId = aid.(int64)
	req.Id = c.Param("id")

	resp, err := global.TripClient.UpdateTrip(ctx, &req)
	if err != nil {
		errno.SendResponse(c, errno.RequestServerFail, nil)
		return
	}

	errno.SendResponse(c, errno.Success, resp)
}
