// Code generated by hertz generator.

package Profile

import (
	"github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/router"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return router.CommentMW()
}

func _profileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_llprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpendingprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsomeprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completeprofilephotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clearprofilephotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprofilephotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createprofilephotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _clearprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _profile0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
