// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/router/auth"
	car "github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/router/car"
	profile "github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/router/profile"
	trip "github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/router/trip"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	trip.Register(r)

	profile.Register(r)

	car.Register(r)

	auth.Register(r)
}
