// Code generated by hertz generator.

package main

import (
	"context"

	"github.com/CyanAsterisk/FreeCar/server/cmd/api/biz/handler"
	"github.com/CyanAsterisk/FreeCar/server/shared/errno"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) { // used for HTTP 404
		errno.SendResponse1(c, errno.BadRequest, nil)
	})
	r.NoMethod(func(ctx context.Context, c *app.RequestContext) { // used for HTTP 405
		errno.SendResponse1(c, errno.BadRequest, nil)
	})
}
