spring.application.name=freecar-trade
server.port=8099

spring.datasource.url=jdbc:mysql://localhost:3306/FreeCar
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=freecar