// Code generated by Kitex v0.4.4. DO NOT EDIT.

package authservice

import (
	"context"
	auth "github.com/CyanAsterisk/FreeCar/server/shared/kitex_gen/auth"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, req *auth.LoginRequest, callOptions ...callopt.Option) (r *auth.LoginResponse, err error)
	AdminLogin(ctx context.Context, req *auth.AdminLoginRequest, callOptions ...callopt.Option) (r *auth.AdminLoginResponse, err error)
	ChangeAdminPassword(ctx context.Context, req *auth.ChangeAdminPasswordRequest, callOptions ...callopt.Option) (r *auth.ChangeAdminPasswordResponse, err error)
	UploadAvatar(ctx context.Context, req *auth.UploadAvatarRequset, callOptions ...callopt.Option) (r *auth.UploadAvatarResponse, err error)
	GetUser(ctx context.Context, req *auth.GetUserRequest, callOptions ...callopt.Option) (r *auth.GetUserInfoResponse, err error)
	AddUser(ctx context.Context, req *auth.AddUserRequest, callOptions ...callopt.Option) (r *auth.AddUserResponse, err error)
	DeleteUser(ctx context.Context, req *auth.DeleteUserRequest, callOptions ...callopt.Option) (r *auth.DeleteUserResponse, err error)
	UpdateUser(ctx context.Context, req *auth.UpdateUserRequest, callOptions ...callopt.Option) (r *auth.UpdateUserResponse, err error)
	GetSomeUsers(ctx context.Context, req *auth.GetSomeUsersRequest, callOptions ...callopt.Option) (r *auth.GetSomeUsersResponse, err error)
	GetAllUsers(ctx context.Context, req *auth.GetAllUsersRequest, callOptions ...callopt.Option) (r *auth.GetAllUsersResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) Login(ctx context.Context, req *auth.LoginRequest, callOptions ...callopt.Option) (r *auth.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kAuthServiceClient) AdminLogin(ctx context.Context, req *auth.AdminLoginRequest, callOptions ...callopt.Option) (r *auth.AdminLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminLogin(ctx, req)
}

func (p *kAuthServiceClient) ChangeAdminPassword(ctx context.Context, req *auth.ChangeAdminPasswordRequest, callOptions ...callopt.Option) (r *auth.ChangeAdminPasswordResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeAdminPassword(ctx, req)
}

func (p *kAuthServiceClient) UploadAvatar(ctx context.Context, req *auth.UploadAvatarRequset, callOptions ...callopt.Option) (r *auth.UploadAvatarResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadAvatar(ctx, req)
}

func (p *kAuthServiceClient) GetUser(ctx context.Context, req *auth.GetUserRequest, callOptions ...callopt.Option) (r *auth.GetUserInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, req)
}

func (p *kAuthServiceClient) AddUser(ctx context.Context, req *auth.AddUserRequest, callOptions ...callopt.Option) (r *auth.AddUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddUser(ctx, req)
}

func (p *kAuthServiceClient) DeleteUser(ctx context.Context, req *auth.DeleteUserRequest, callOptions ...callopt.Option) (r *auth.DeleteUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUser(ctx, req)
}

func (p *kAuthServiceClient) UpdateUser(ctx context.Context, req *auth.UpdateUserRequest, callOptions ...callopt.Option) (r *auth.UpdateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, req)
}

func (p *kAuthServiceClient) GetSomeUsers(ctx context.Context, req *auth.GetSomeUsersRequest, callOptions ...callopt.Option) (r *auth.GetSomeUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSomeUsers(ctx, req)
}

func (p *kAuthServiceClient) GetAllUsers(ctx context.Context, req *auth.GetAllUsersRequest, callOptions ...callopt.Option) (r *auth.GetAllUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAllUsers(ctx, req)
}
