// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tradeservice

import (
	"context"
	trade "github.com/CyanAsterisk/FreeCar/server/shared/kitex_gen/trade"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Pay(ctx context.Context, request *trade.PayRequest, callOptions ...callopt.Option) (r *trade.PayResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTradeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTradeServiceClient struct {
	*kClient
}

func (p *kTradeServiceClient) Pay(ctx context.Context, request *trade.PayRequest, callOptions ...callopt.Option) (r *trade.PayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Pay(ctx, request)
}
