// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tradeservice

import (
	"context"
	trade "github.com/CyanAsterisk/FreeCar/server/shared/kitex_gen/trade"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return tradeServiceServiceInfo
}

var tradeServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "TradeService"
	handlerType := (*trade.TradeService)(nil)
	methods := map[string]kitex.MethodInfo{
		"pay": kitex.NewMethodInfo(payHandler, newTradeServicePayArgs, newTradeServicePayResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "trade",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func payHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trade.TradeServicePayArgs)
	realResult := result.(*trade.TradeServicePayResult)
	success, err := handler.(trade.TradeService).Pay(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTradeServicePayArgs() interface{} {
	return trade.NewTradeServicePayArgs()
}

func newTradeServicePayResult() interface{} {
	return trade.NewTradeServicePayResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Pay(ctx context.Context, request *trade.PayRequest) (r *trade.PayResponse, err error) {
	var _args trade.TradeServicePayArgs
	_args.Request = request
	var _result trade.TradeServicePayResult
	if err = p.c.Call(ctx, "pay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
