name: Tests

on: [ push, pull_request ]

jobs:
  CI:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Configure Docker daemon
        run: |
          sudo mkdir -p /etc/docker
          echo '{ "experimental": true, "features": { "buildkit": true } }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker || sudo service docker restart

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          docker pull mongo:latest
          docker pull mysql:latest
          docker pull redis:latest

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Unit Test
        run: go test ./...